Repository AY2324S1-CS2103T-W16-3/tp, pull requests merged in 2023-11, with the labels that each got.

#124 Fix help window to direct to InsureIQ User Guide
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.high

#130 Update UG for Find, Remind and Remark feature
  docs/UserGuide.md
  docs/images/FindSuccess.png
  docs/images/RemarkSuccess.png
  docs/images/RemindSuccess.png
  docs/images/Ui.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/model/person/RemindPredicate.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
Labels: documentation

#131 Update UG codeblock to make it more readable
  docs/UserGuide.md
Labels: documentation

#137 Change the name of the storage file to insureiq.json
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.high

#136 Fix prefix for Contact Number field in UG for Find Feature
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: documentation

#215 Update PPP for Brendan
  docs/DeveloperGuide.md
  docs/team/brendanneojw.md
  src/main/java/seedu/address/model/person/CompanyContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PolicyExpiryContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PolicyIssueContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/RemindPredicate.java
Labels: documentation

#219 Update tests for Model and Storage for new attributes
  src/main/java/seedu/address/model/person/LicencePlate.java
  src/main/java/seedu/address/model/policy/Company.java
  src/main/java/seedu/address/model/policy/Policy.java
  src/main/java/seedu/address/model/policy/PolicyDate.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/model/person/LicencePlateTest.java
  src/test/java/seedu/address/model/person/NricTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
  src/test/java/seedu/address/model/policy/CompanyTest.java
  src/test/java/seedu/address/model/policy/PolicyDateTest.java
  src/test/java/seedu/address/model/policy/PolicyNumberTest.java
  src/test/java/seedu/address/model/policy/PolicyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: testing

#223 Add tests for remind command and enhanced features
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/model/person/predicates/PolicyNumberContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/RemindPredicate.java
  src/main/java/seedu/address/model/policy/PolicyNumber.java
  src/test/java/seedu/address/logic/commands/RemindCommandTest.java
  src/test/java/seedu/address/logic/parser/RemindCommandParserTest.java
  src/test/java/seedu/address/model/person/predicates/CompanyContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/LicenceContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/NricContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/PolicyExpiryContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/PolicyIssueContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/PolicyNumberContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/RemindPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/policy/PolicyTest.java
Labels: testing

#224 Change and standardise documentation and code
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/assets/css/style.scss
  docs/images/AddSuccess.png
  docs/images/BatchDeleteSuccess.png
  docs/images/DeleteSuccess.png
  docs/images/EditSuccess.png
  docs/images/FindSuccess.png
  docs/images/RemarkSuccess.png
  docs/images/RemindSuccess.png
  docs/images/SortSuccess.png
  docs/images/Ui.png
  docs/team/cyaoxuan.md
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/month/DeleteMonth.java
  src/main/java/seedu/address/model/policy/Company.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: documentation

#235 Add Planned Enhancements in DG
  docs/DeveloperGuide.md
  docs/images/CommandFail.png
  docs/images/CommandSuccess.png
  docs/images/DeletePolicyFromEdit.png
  docs/team/brendanneojw.md
Labels: documentation

#239 Add tests for FindCommandParser.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: testing

#241 Add tests for Remark Parser
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
Labels: testing

#243 Update Developer Guide
  docs/DeveloperGuide.md
Labels: documentation

#245 Refine tests in for FindCommand.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: testing

#247 Refine UG for Find section
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/brendanneojw.md
Labels: documentation

#255 Update UG
  docs/UserGuide.md
  docs/team/cyaoxuan.md
Labels: documentation

#256 Fix sequence diagrams bugs
  docs/diagrams/RemindSequenceDiagram2.puml
  docs/diagrams/SortSequenceDiagram1.puml
  docs/diagrams/SortSequenceDiagram2.puml
  docs/images/RemindSequenceDiagram2.png
  docs/images/SortSequenceDiagram1.png
  docs/images/SortSequenceDiagram2.png
  docs/team/rsxix.md
Labels: documentation

#261 Fix UG with the group
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
Labels: documentation

#262 Update DG halfway
  docs/DeveloperGuide.md
  docs/diagrams/RemindSequenceDiagram1.puml
  docs/images/RemindSequenceDiagram1.png
Labels: documentation

#266 Fix DG bugs
  docs/DeveloperGuide.md
Labels: documentation
